"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English (EN)" },
  { code: "hi", name: "Hindi", nativeName: "हिंदी (Hindi)" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ (Kannada)" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ் (Tamil)" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు (Telugu)" },
  { code: "mr", name: "Marathi", nativeName: "मराठी (Marathi)" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা (Bengali)" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം (Malayalam)" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી (Gujarati)" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ (Punjabi)" },
  { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ (Odia)" }
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    // Header & Brand
    gov_india: "GOVERNMENT OF INDIA",
    bis_title: "Bureau of Indian Standards (BIS)",
    demo_prototype: "DEMO DATA PROTOTYPE",
    manakonline: "Manakonline",
    app_title: "NexaStandards",
    app_badge: "SIH26107 Assistant",
    app_subtitle: "From scattered standards documents to trusted, actionable compliance support.",
    nav_assistant: "AI Assistant",
    nav_verify: "Verify Product",
    nav_standards: "Standards & QCO",
    nav_compliance: "Compliance Roadmap",
    nav_labs: "Testing Labs",
    nav_hallmarking: "Hallmarking",
    nav_grievance: "Consumer Grievance",
    nav_admin: "Admin Portal",

    // Sidebar
    sih_statement: "SIH Problem Statement 26107",
    engine_name: "NexaStandards Engine",
    tagline: "Ask · Understand · Verify · Act",
    side_group1: "1. ASK IN ONE PLACE",
    side_group2: "2. UNDERSTAND BIS DOCS",
    side_group3: "3. VERIFY PRODUCTS FAST",
    side_group4: "4. TAKE THE NEXT ACTION",
    side_group5: "5. REPOSITORY & ADMIN",
    side_assistant: "AI Conversational Assistant",
    side_standards: "Standards & QCO Explorer",
    side_compare: "Standard Comparison Matrix",
    side_certification: "Certification Schemes",
    side_testing: "Testing Requirements",
    side_verify: "Product Verification (OCR)",
    side_hallmarking: "Gold Hallmarking & HUID",
    side_compliance: "Compliance Roadmap",
    side_labs: "Testing Laboratory Matcher",
    side_grievance: "BIS Grievance Assistant",
    side_profile: "User Profile",
    side_settings: "Settings & LLM",
    side_admin_rag: "Knowledge Specs & RAG",
    side_admin_docs: "Document Registry & Ingestion",

    // Home Page Hero
    hero_title: "Tell us what product you have or want to make.",
    hero_subtitle: "NexaStandards translates complex BIS statutory regulations, Indian Standards, and Gazette QCOs into plain, actionable guidance tailored to your specific role.",

    // 3 Persona Choice Cards
    persona_consumer_title: "I am a Consumer",
    persona_consumer_desc: "Check a product, BIS mark, licence or requirement",
    persona_consumer_action: "Verify Mark & Packaging →",
    persona_consumer_badge: "PLAIN LANGUAGE",

    persona_startup_title: "I am a Startup / MSME",
    persona_startup_desc: "Find what I need to manufacture or sell this product",
    persona_startup_action: "Startup Manufacturing Guide →",
    persona_startup_badge: "14-POINT CHECKLIST",

    persona_builder_title: "I am a Product Builder",
    persona_builder_desc: "Get standards, tests, documents and certification requirements",
    persona_builder_action: "Clauses & Test Parameters →",
    persona_builder_badge: "ENGINEERING SPECS",

    // Search Box & Role Bar
    search_role_prefix: "SEARCH REGULATORY INTELLIGENCE (ACTIVE ROLE: ",
    search_role_suffix: ")",
    switch_role: "Switch Role:",
    role_consumer: "Consumer",
    role_startup: "Startup",
    role_builder: "Builder",
    search_placeholder: "e.g. 'mobile', 'What standard applies to pressure cookers?', 'ಕನ್ನಡ: ಈ ಪ್ರೆಶರ್ ಕುಕ್ಕರ್‌ಗೆ BIS ಬೇಕಾ?'",
    search_button: "Search Regulatory Intelligence →",
    try_scenarios: "Try Instant Scenarios:",
    verify_photo_button: "Verify Mark / Photo",

    // Quick Actions
    qa_title: "Quick Regulatory Actions",
    qa_search_std: "Search Standards",
    qa_search_std_desc: "Explore operative IS specifications",
    qa_verify_prod: "Verify Product",
    qa_verify_prod_desc: "Scan label or enter CM/L number",
    qa_check_mark: "Check BIS Mark",
    qa_check_mark_desc: "Verify ISI Mark, CRS R-No, or Hallmark",
    qa_cert_help: "Certification Help",
    qa_cert_help_desc: "MSME 6-stage compliance roadmap",
    qa_find_lab: "Find Laboratory",
    qa_find_lab_desc: "BIS-recognized NABL testing facilities",
    qa_report_complaint: "Report Complaint",
    qa_report_complaint_desc: "Draft BIS Act 2016 grievance dossier",

    // Showcase & Judge Section
    diff_badge: "JUDGE BENCHMARK SHOWCASE",
    diff_title: "Docling + BGE-M3 Semantic Change Detection (Zero Hashing)",
    diff_desc: "Demonstrating clause-by-clause versioning and regulatory impact analysis per judge requirements.",
    diff_demo1: "IS 2347:2017 Clause 5.2 (Modified)",
    diff_demo2: "IS 17803:2022 (Added Clause)",
    diff_demo3: "IS 13252:2010 (Moved / Renamed Clause)",

    // Assistant Page
    assistant_welcome: "Namaste! I am NexaStandards, your evidence-grounded AI assistant for Indian Standards and BIS services (SIH 2026 · Problem SIH26107). Ask about any product (e.g., 'mobile', 'pressure cooker', 'water bottle'), standard, testing parameter, or Gazette order to receive verified, clause-grounded regulatory guidance.",
    tab_consumer: "🛒 Consumer Mark Verification",
    tab_startup: "🚀 Startup / MSME 14-Stage Roadmap",
    tab_builder: "🏭 Product Builder & Technical Specs",
    glossary_btn: "What Does This BIS Term Mean?",
    input_placeholder: "Ask NexaStandards about any standard, QCO, or product...",
    send_btn: "Ask NexaStandards",
    listening: "Listening... speak now",
    source_locked: "SOURCE-LOCKED",
    unverified: "UNVERIFIED"
  },

  hi: {
    // Header & Brand
    gov_india: "भारत सरकार",
    bis_title: "भारतीय मानक ब्यूरो (BIS)",
    demo_prototype: "प्रोटोटाइप डेमो",
    manakonline: "मानकऑनलाइन",
    app_title: "नेक्सामानक",
    app_badge: "SIH26107 सहायक",
    app_subtitle: "भारतीय मानकों और विनियमों के लिए प्रामाणिक एवं भरोसेमंद अनुपालन सहायता।",
    nav_assistant: "AI सहायक",
    nav_verify: "उत्पाद सत्यापन",
    nav_standards: "मानक एवं QCO",
    nav_compliance: "अनुपालन रोडमैप",
    nav_labs: "परीक्षण प्रयोगशालाएं",
    nav_hallmarking: "हॉलमार्किंग",
    nav_grievance: "उपभोक्ता शिकायत",
    nav_admin: "एडमिन पोर्टल",

    // Sidebar
    sih_statement: "SIH समस्या कथन 26107",
    engine_name: "नेक्सामानक इंजन",
    tagline: "पूछें · समझें · सत्यापित करें · कार्य करें",
    side_group1: "1. एक ही स्थान पर पूछें",
    side_group2: "2. BIS नियमों को समझें",
    side_group3: "3. त्वरित उत्पाद सत्यापन",
    side_group4: "4. अगला कदम उठाएं",
    side_group5: "5. प्रशासनिक रजिस्ट्री",
    side_assistant: "AI संवादात्मक सहायक",
    side_standards: "मानक एवं QCO खोज",
    side_compare: "मानक तुलना मैट्रिक्स",
    side_certification: "प्रमाणन योजनाएं",
    side_testing: "परीक्षण आवश्यकताएं",
    side_verify: "उत्पाद सत्यापन (OCR)",
    side_hallmarking: "स्वर्ण हॉलमार्किंग एवं HUID",
    side_compliance: "अनुपालन रोडमैप",
    side_labs: "प्रयोगशाला मिलान",
    side_grievance: "BIS शिकायत सहायक",
    side_profile: "उपयोगकर्ता प्रोफ़ाइल",
    side_settings: "सेटिंग्स एवं LLM",
    side_admin_rag: "नॉलेज स्पेक्स एवं RAG",
    side_admin_docs: "दस्तावेज़ रजिस्ट्री",

    // Home Page Hero
    hero_title: "बताएं कि आपके पास कौन सा उत्पाद है या आप क्या बनाना चाहते हैं।",
    hero_subtitle: "नेक्सामानक जटिल BIS वैधानिक नियमों, भारतीय मानकों और गजट QCO को आपकी भूमिका के अनुसार सरल, व्यावहारिक मार्गदर्शन में अनुवादित करता है।",

    // 3 Persona Choice Cards
    persona_consumer_title: "मैं एक उपभोक्ता हूँ",
    persona_consumer_desc: "किसी उत्पाद, BIS चिह्न, लाइसेंस या आवश्यकता की जाँच करें",
    persona_consumer_action: "मार्क एवं पैकेजिंग सत्यापित करें →",
    persona_consumer_badge: "सरल भाषा",

    persona_startup_title: "मैं एक स्टार्टअप / MSME हूँ",
    persona_startup_desc: "जानें कि इस उत्पाद को बनाने या बेचने के लिए मुझे क्या चाहिए",
    persona_startup_action: "स्टार्टअप विनिर्माण गाइड →",
    persona_startup_badge: "14-चरणीय चेकलिस्ट",

    persona_builder_title: "मैं एक उत्पाद निर्माता / इंजीनियर हूँ",
    persona_builder_desc: "मानक, परीक्षण, दस्तावेज और प्रमाणन आवश्यकताएं प्राप्त करें",
    persona_builder_action: "क्लॉज एवं परीक्षण पैरामीटर →",
    persona_builder_badge: "इंजीनियरिंग विनिर्देश",

    // Search Box & Role Bar
    search_role_prefix: "नियामक जानकारी खोजें (सक्रिय भूमिका: ",
    search_role_suffix: ")",
    switch_role: "भूमिका बदलें:",
    role_consumer: "उपभोक्ता",
    role_startup: "स्टार्टअप",
    role_builder: "इंजीनियर",
    search_placeholder: "उदा. 'मोबाइल', 'प्रेशर कुकर पर कौन सा मानक लागू होता है?'...",
    search_button: "नियामक जानकारी खोजें →",
    try_scenarios: "त्वरित उदाहरण देखें:",
    verify_photo_button: "मार्क / फोटो सत्यापित करें",

    // Quick Actions
    qa_title: "त्वरित नियामक कार्य",
    qa_search_std: "मानक खोजें",
    qa_search_std_desc: "लागू भारतीय मानक विनिर्देश देखें",
    qa_verify_prod: "उत्पाद सत्यापित करें",
    qa_verify_prod_desc: "लेबल स्कैन करें या CM/L नंबर दर्ज करें",
    qa_check_mark: "BIS मार्क जांचें",
    qa_check_mark_desc: "ISI मार्क, CRS R-नंबर, या हॉलमार्क सत्यापित करें",
    qa_cert_help: "प्रमाणन सहायता",
    qa_cert_help_desc: "MSME 6-चरणीय अनुपालन रोडमैप",
    qa_find_lab: "प्रयोगशाला खोजें",
    qa_find_lab_desc: "BIS-मान्यता प्राप्त NABL परीक्षण प्रयोगशालाएं",
    qa_report_complaint: "शिकायत दर्ज करें",
    qa_report_complaint_desc: "BIS अधिनियम 2016 के तहत शिकायत डोजियर बनाएं",

    // Showcase & Judge Section
    diff_badge: "न्यायाधीश बेंचमार्क प्रदर्शन",
    diff_title: "डॉकलिंग + BGE-M3 सिमेंटिक परिवर्तन पहचान (शून्य हैशिंग)",
    diff_desc: "न्यायाधीशों की आवश्यकता के अनुसार क्लॉज-दर-क्लॉज दस्तावेज़ संस्करण और नियामक प्रभाव विश्लेषण।",
    diff_demo1: "IS 2347:2017 क्लॉज 5.2 (संशोधित)",
    diff_demo2: "IS 17803:2022 (नया क्लॉज जोड़ा गया)",
    diff_demo3: "IS 13252:2010 (पुनः क्रमांकित क्लॉज)",

    // Assistant Page
    assistant_welcome: "नमस्ते! मैं नेक्सामानक हूँ, भारतीय मानकों और BIS सेवाओं के लिए आपका साक्ष्य-आधारित AI सहायक। सत्यापित, क्लॉज-आधारित मार्गदर्शन प्राप्त करने के लिए किसी भी उत्पाद (जैसे 'मोबाइल', 'प्रेशर कुकर'), मानक, परीक्षण पैरामीटर या गजट आदेश के बारे में पूछें।",
    tab_consumer: "🛒 उपभोक्ता मार्क सत्यापन",
    tab_startup: "🚀 स्टार्टअप / MSME 14-चरणीय रोडमैप",
    tab_builder: "🏭 उत्पाद निर्माता तकनीकी विनिर्देश",
    glossary_btn: "इस BIS शब्द का क्या अर्थ है?",
    input_placeholder: "नेक्सामानक से किसी भी मानक, QCO या उत्पाद के बारे में पूछें...",
    send_btn: "पूछें",
    listening: "सुन रहे हैं... अब बोलें",
    source_locked: "स्रोत-सत्यापित",
    unverified: "असत्यापित"
  },

  kn: {
    // Header & Brand
    gov_india: "ಭಾರತ ಸರ್ಕಾರ",
    bis_title: "ಭಾರತೀಯ ಮಾನಕ ಬ್ಯೂರೋ (BIS)",
    demo_prototype: "ಪ್ರಾಯೋಗಿಕ ಮಾದರಿ",
    manakonline: "ಮಾನಕಆನ್‌ಲೈನ್",
    app_title: "ನೆಕ್ಸಾಮಾನಕ",
    app_badge: "SIH26107 ಸಹಾಯಕ",
    app_subtitle: "ಭಾರತೀಯ ಮಾನದಂಡಗಳು ಮತ್ತು ನಿಯಮಾವಳಿಗಳಿಗೆ ವಿಶ್ವಾಸಾರ್ಹ ಮತ್ತು ನಿಖರವಾದ ಅನುಸರಣಾ ಬೆಂಬಲ.",
    nav_assistant: "AI ಸಹಾಯಕ",
    nav_verify: "ಉತ್ಪನ್ನ ಪರಿಶೀಲನೆ",
    nav_standards: "ಮಾನದಂಡಗಳು & QCO",
    nav_compliance: "ಅನುಸರಣೆ ಮಾರ್ಗಸೂಚಿ",
    nav_labs: "ಪರೀಕ್ಷಾ ಪ್ರಯೋಗಾಲಯಗಳು",
    nav_hallmarking: "ಹಾಲ್‌ಮಾರ್ಕಿಂಗ್",
    nav_grievance: "ಗ್ರಾಹಕರ ದೂರು",
    nav_admin: "ನಿರ್ವಾಹಕ ಪೋರ್ಟಲ್",

    // Sidebar
    sih_statement: "SIH ಸಮಸ್ಯೆ ಹೇಳಿಕೆ 26107",
    engine_name: "ನೆಕ್ಸಾಮಾನಕ ಎಂಜಿನ್",
    tagline: "ಕೇಳಿ · ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ · ಪರಿಶೀಲಿಸಿ · ಕಾರ್ಯನಿರ್ವಹಿಸಿ",
    side_group1: "1. ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ ಕೇಳಿ",
    side_group2: "2. BIS ನಿಯಮಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ",
    side_group3: "3. ತ್ವರಿತ ಉತ್ಪನ್ನ ಪರಿಶೀಲನೆ",
    side_group4: "4. ಮುಂದಿನ ಕ್ರಮ ಕೈಗೊಳ್ಳಿ",
    side_group5: "5. ಶಾಸನಬದ್ಧ ದಾಖಲೆಗಳು",
    side_assistant: "AI ಸಂಭಾಷಣಾ ಸಹಾಯಕ",
    side_standards: "ಮಾನದಂಡಗಳು & QCO ಅನ್ವೇಷಕ",
    side_compare: "ಮಾನದಂಡ ಹೋಲಿಕೆ ಕೋಷ್ಟಕ",
    side_certification: "ಪ್ರಮಾಣೀಕರಣ ಯೋಜನೆಗಳು",
    side_testing: "ಪರೀಕ್ಷಾ ಅಗತ್ಯತೆಗಳು",
    side_verify: "ಉತ್ಪನ್ನ ಪರಿಶೀಲನೆ (OCR)",
    side_hallmarking: "ಚಿನ್ನದ ಹಾಲ್‌ಮಾರ್ಕಿಂಗ್ & HUID",
    side_compliance: "ಅನುಸರಣೆ ಮಾರ್ಗಸೂಚಿ",
    side_labs: "ಪ್ರಯೋಗಾಲಯ ಹೊಂದಾಣಿಕೆ",
    side_grievance: "BIS ದೂರು ಸಹಾಯಕ",
    side_profile: "ಬಳಕೆದಾರರ ಪ್ರೊಫೈಲ್",
    side_settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು & LLM",
    side_admin_rag: "ಜ್ಞಾನದ ವಿವರಗಳು & RAG",
    side_admin_docs: "ದಾಖಲೆಗಳ ನೋಂದಣಿ",

    // Home Page Hero
    hero_title: "ನಿಮ್ಮಲ್ಲಿ ಯಾವ ಉತ್ಪನ್ನವಿದೆ ಅಥವಾ ನೀವು ಏನನ್ನು ತಯಾರಿಸಲು ಬಯಸುತ್ತೀರಿ ಎಂದು ತಿಳಿಸಿ.",
    hero_subtitle: "ನೆಕ್ಸಾಮಾನಕವು ಸಂಕೀರ್ಣ BIS ಶಾಸನಬದ್ಧ ನಿಯಮಗಳು, ಭಾರತೀಯ ಮಾನದಂಡಗಳು ಮತ್ತು ಗೆಜೆಟ್ QCO ಗಳನ್ನು ನಿಮ್ಮ ನಿರ್ದಿಷ್ಟ ಪಾತ್ರಕ್ಕೆ ತಕ್ಕಂತೆ ಸರಳ ಮತ್ತು ಸ್ಪಷ್ಟ ಮಾರ್ಗದರ್ಶನವಾಗಿ ಪರಿವರ್ತಿಸುತ್ತದೆ.",

    // 3 Persona Choice Cards
    persona_consumer_title: "ನಾನು ಗ್ರಾಹಕ",
    persona_consumer_desc: "ಉತ್ಪನ್ನ, BIS ಗುರುತು, ಪರವಾನಗಿ ಅಥವಾ ಅಗತ್ಯತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ",
    persona_consumer_action: "ಗುರುತು & ಪ್ಯಾಕೇಜಿಂಗ್ ಪರಿಶೀಲಿಸಿ →",
    persona_consumer_badge: "ಸರಳ ಭಾಷೆ",

    persona_startup_title: "ನಾನು ಸ್ಟಾರ್ಟ್ಅಪ್ / MSME",
    persona_startup_desc: "ಈ ಉತ್ಪನ್ನವನ್ನು ತಯಾರಿಸಲು ಅಥವಾ ಮಾರಾಟ ಮಾಡಲು ನನಗೆ ಏನು ಬೇಕು ಎಂದು ತಿಳಿಯಿರಿ",
    persona_startup_action: "ಸ್ಟಾರ್ಟ್ಅಪ್ ತಯಾರಿಕಾ ಮಾರ್ಗದರ್ಶಿ →",
    persona_startup_badge: "14-ಹಂತಗಳ ಪರಿಶೀಲನಾಪಟ್ಟಿ",

    persona_builder_title: "ನಾನು ಉತ್ಪನ್ನ ತಯಾರಕ / ಎಂಜಿನಿಯರ್",
    persona_builder_desc: "ಮಾನದಂಡಗಳು, ಪರೀಕ್ಷೆಗಳು, ದಾಖಲೆಗಳು ಮತ್ತು ಪ್ರಮಾಣೀಕರಣ ಅಗತ್ಯತೆಗಳನ್ನು ಪಡೆಯಿರಿ",
    persona_builder_action: "ಷರತ್ತುಗಳು & ಪರೀಕ್ಷಾ ನಿಯತಾಂಕಗಳು →",
    persona_builder_badge: "ಎಂಜಿನಿಯರಿಂಗ್ ವಿವರಣೆಗಳು",

    // Search Box & Role Bar
    search_role_prefix: "ಶಾಸನಬದ್ಧ ಮಾಹಿತಿ ಹುಡುಕಿ (ಸಕ್ರಿಯ ಪಾತ್ರ: ",
    search_role_suffix: ")",
    switch_role: "ಪಾತ್ರ ಬದಲಾಯಿಸಿ:",
    role_consumer: "ಗ್ರಾಹಕ",
    role_startup: "ಸ್ಟಾರ್ಟ್ಅಪ್",
    role_builder: "ಎಂಜಿನಿಯರ್",
    search_placeholder: "ಉದಾ: 'ಮೊಬೈಲ್', 'ಪ್ರೆಶರ್ ಕುಕ್ಕರ್‌ಗೆ ಯಾವ ಮಾನದಂಡ ಅನ್ವಯಿಸುತ್ತದೆ?'...",
    search_button: "ಶಾಸನಬದ್ಧ ಮಾಹಿತಿ ಹುಡುಕಿ →",
    try_scenarios: "ತ್ವರಿತ ಉದಾಹರಣೆಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿ:",
    verify_photo_button: "ಗುರುತು / ಫೋಟೋ ಪರಿಶೀಲಿಸಿ",

    // Quick Actions
    qa_title: "ತ್ವರಿತ ಶಾಸನಬದ್ಧ ಕ್ರಮಗಳು",
    qa_search_std: "ಮಾನದಂಡಗಳನ್ನು ಹುಡುಕಿ",
    qa_search_std_desc: "ಅನ್ವಯವಾಗುವ IS ವಿವರಣೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    qa_verify_prod: "ಉತ್ಪನ್ನ ಪರಿಶೀಲಿಸಿ",
    qa_verify_prod_desc: "ಲೇಬಲ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಅಥವಾ CM/L ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    qa_check_mark: "BIS ಮಾರ್ಕ್ ಪರಿಶೀಲಿಸಿ",
    qa_check_mark_desc: "ISI ಮಾರ್ಕ್, CRS R-ಸಂಖ್ಯೆ, ಅಥವಾ ಹಾಲ್‌ಮಾರ್ಕ್ ಪರಿಶೀಲಿಸಿ",
    qa_cert_help: "ಪ್ರಮಾಣೀಕರಣ ಸಹಾಯ",
    qa_cert_help_desc: "MSME 6-ಹಂತಗಳ ಅನುಸರಣಾ ಮಾರ್ಗಸೂಚಿ",
    qa_find_lab: "ಪ್ರಯೋಗಾಲಯ ಹುಡುಕಿ",
    qa_find_lab_desc: "BIS ಮಾನ್ಯತೆ ಪಡೆದ NABL ಪರೀಕ್ಷಾ ಕೇಂದ್ರಗಳು",
    qa_report_complaint: "ದೂರು ದಾಖಲಿಸಿ",
    qa_report_complaint_desc: "BIS ಕಾಯ್ದೆ 2016 ರ ಅಡಿಯಲ್ಲಿ ದೂರು ದಾಖಲೆ ಸಿದ್ಧಪಡಿಸಿ",

    // Showcase & Judge Section
    diff_badge: "ತೀರ್ಪುಗಾರರ ಬೆಂಚ್‌ಮಾರ್ಕ್ ಪ್ರಾತ್ಯಕ್ಷಿಕೆ",
    diff_title: "ಡಾಕ್ಲಿಂಗ್ + BGE-M3 ಸಿಮ್ಯಾಂಟಿಕ್ ಬದಲಾವಣೆ ಪತ್ತೆ (ಶೂನ್ಯ ಹ್ಯಾಶಿಂಗ್)",
    diff_desc: "ತೀರ್ಪುಗಾರರ ಅಗತ್ಯತೆಯಂತೆ ಷರತ್ತುವಾರು ಆವೃತ್ತಿ ಮತ್ತು ನಿಯಂತ್ರಕ ಪ್ರಭಾವ ವಿಶ್ಲೇಷಣೆ.",
    diff_demo1: "IS 2347:2017 ಷರತ್ತು 5.2 (ಮಾರ್ಪಡಿಸಲಾಗಿದೆ)",
    diff_demo2: "IS 17803:2022 (ಹೊಸ ಷರತ್ತು ಸೇರಿಸಲಾಗಿದೆ)",
    diff_demo3: "IS 13252:2010 (ಮರುಕ್ರಮಾಂಕಿತ ಷರತ್ತು)",

    // Assistant Page
    assistant_welcome: "ನಮಸ್ಕಾರ! ನಾನು ನೆಕ್ಸಾಮಾನಕ, ಭಾರತೀಯ ಮಾನದಂಡಗಳು ಮತ್ತು BIS ಸೇವೆಗಳಿಗಾಗಿ ನಿಮ್ಮ ಸಾಕ್ಷ್ಯಾಧಾರಿತ AI ಸಹಾಯಕ. ಯಾವುದೇ ಉತ್ಪನ್ನ (ಉದಾ: 'ಮೊಬೈಲ್', 'ಪ್ರೆಶರ್ ಕುಕ್ಕರ್'), ಮಾನದಂಡ ಅಥವಾ ಗೆಜೆಟ್ ಆದೇಶದ ಬಗ್ಗೆ ಕೇಳಿ ಪರಿಶೀಲಿಸಿದ ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಿರಿ.",
    tab_consumer: "🛒 ಗ್ರಾಹಕ ಮಾರ್ಕ್ ಪರಿಶೀಲನೆ",
    tab_startup: "🚀 ಸ್ಟಾರ್ಟ್ಅಪ್ / MSME 14-ಹಂತಗಳ ಮಾರ್ಗಸೂಚಿ",
    tab_builder: "🏭 ಉತ್ಪನ್ನ ತಯಾರಕರ ತಾಂತ್ರಿಕ ವಿವರಣೆಗಳು",
    glossary_btn: "ಈ BIS ಪದದ ಅರ್ಥವೇನು?",
    input_placeholder: "ಯಾವುದೇ ಮಾನದಂಡ, QCO ಅಥವಾ ಉತ್ಪನ್ನದ ಬಗ್ಗೆ ನೆಕ್ಸಾಮಾನಕವನ್ನು ಕೇಳಿ...",
    send_btn: "ಕೇಳಿ",
    listening: "ಆಲಿಸುತ್ತಿದೆ... ಮಾತನಾಡಿ",
    source_locked: "ಮೂಲ-ದೃಢೀಕೃತ",
    unverified: "ಅಪರಿಶೀಲಿತ"
  },

  ta: {
    gov_india: "இந்திய அரசு",
    bis_title: "இந்தியத் தர நிர்ணயப் பணியகம் (BIS)",
    demo_prototype: "மாதிரி டெமோ",
    manakonline: "மானக்ஆன்லைன்",
    app_title: "நெக்ஸாமாதிரி",
    app_badge: "SIH26107 உதவியாளர்",
    app_subtitle: "இந்தியத் தரநிலைகள் மற்றும் விதிமுறைகளுக்கான நம்பகமான மற்றும் துல்லியமான இணக்க ஆதரவு.",
    nav_assistant: "AI உதவியாளர்",
    nav_verify: "தயாரிப்பு சரிபார்ப்பு",
    nav_standards: "தரநிலைகள் & QCO",
    nav_compliance: "இணக்க வழிகாட்டி",
    nav_labs: "சோதனை ஆய்வகங்கள்",
    nav_hallmarking: "ஹால்மார்க்கிங்",
    nav_grievance: "நுகர்வோர் புகார்",
    nav_admin: "நிர்வாகி போர்டல்",
    side_group1: "1. ஒரே இடத்தில் கேளுங்கள்",
    side_group2: "2. BIS விதிகளைப் புரிந்து கொள்ளுங்கள்",
    side_group3: "3. விரைவான தயாரிப்பு சரிபார்ப்பு",
    side_group4: "4. அடுத்த நடவடிக்கை எடுங்கள்",
    side_group5: "5. சட்டப்பூர்வ பதிவேடு",
    side_assistant: "AI உரையாடல் உதவியாளர்",
    side_standards: "தரநிலைகள் & QCO உலாவி",
    side_compare: "தரநிலை ஒப்பீட்டு அட்டவணை",
    side_certification: "சான்றிதழ் திட்டங்கள்",
    side_testing: "சோதனைத் தேவைகள்",
    side_verify: "தயாரிப்பு சரிபார்ப்பு (OCR)",
    side_hallmarking: "தங்க ஹால்மார்க்கிங் & HUID",
    side_compliance: "இணக்க வழிகாட்டி",
    side_labs: "ஆய்வகப் பொருத்தம்",
    side_grievance: "BIS புகார் உதவியாளர்",
    side_profile: "பயனர் சுயவிவரம்",
    side_settings: "அமைப்புகள் & LLM",
    side_admin_rag: "அறிவு விவரக்குறிப்புகள் & RAG",
    side_admin_docs: "ஆவணப் பதிவு",
    hero_title: "உங்களிடம் எந்த தயாரிப்பு உள்ளது அல்லது எதைத் தயாரிக்க விரும்புகிறீர்கள் என்று சொல்லுங்கள்.",
    hero_subtitle: "சிக்கலான BIS சட்டப்பூர்வ விதிமுறைகள், இந்தியத் தரநிலைகள் மற்றும் அரசாணை QCO-க்களை உங்கள் பங்கிற்கு ஏற்ப எளிய வழிகாட்டுதலாக மாற்றுகிறது.",
    persona_consumer_title: "நான் ஒரு நுகர்வோர்",
    persona_consumer_desc: "தயாரிப்பு, BIS முத்திரை, உரிமம் அல்லது தேவையை சரிபார்க்கவும்",
    persona_consumer_action: "முத்திரை & பேக்கேஜிங் சரிபார்க்கவும் →",
    persona_consumer_badge: "எளிய மொழி",
    persona_startup_title: "நான் ஒரு ஸ்டார்ட்அப் / MSME",
    persona_startup_desc: "இதைத் தயாரிக்க அல்லது விற்க எனக்கு என்ன தேவை என்பதை அறியவும்",
    persona_startup_action: "ஸ்டார்ட்அப் தயாரிப்பு வழிகாட்டி →",
    persona_startup_badge: "14-படி சரிபார்ப்பு பட்டியல்",
    persona_builder_title: "நான் ஒரு தயாரிப்பாளர் / பொறியாளர்",
    persona_builder_desc: "தரநிலைகள், சோதனைகள் மற்றும் சான்றிதழ் தேவைகளைப் பெறுங்கள்",
    persona_builder_action: "பிரிவுகள் & சோதனை அளவுருக்கள் →",
    persona_builder_badge: "பொறியியல் விவரக்குறிப்புகள்",
    search_role_prefix: "ஒழுங்குமுறை தகவலைத் தேடுங்கள் (செயலில் உள்ள பங்கு: ",
    search_role_suffix: ")",
    switch_role: "பங்கு மாற்றவும்:",
    role_consumer: "நுகர்வோர்",
    role_startup: "ஸ்டார்ட்அப்",
    role_builder: "பொறியாளர்",
    search_placeholder: "எ.கா. 'மொபைல்', 'பிரஷர் குக்கருக்கு எந்தத் தரம் பொருந்தும்?'...",
    search_button: "ஒழுங்குமுறை தகவலைத் தேடுங்கள் →",
    try_scenarios: "விரைவான உதாரணங்களை முயற்சிக்கவும்:",
    verify_photo_button: "முத்திரை / புகைப்படத்தை சரிபார்க்கவும்",
    qa_title: "விரைவான நடவடிக்கைகள்",
    qa_search_std: "தரநிலைகளைத் தேடுங்கள்",
    qa_search_std_desc: "பொருந்தக்கூடிய IS விவரக்குறிப்புகளை ஆராயுங்கள்",
    qa_verify_prod: "தயாரிப்பைச் சரிபார்க்கவும்",
    qa_verify_prod_desc: "லேபிளை ஸ்கேன் செய்யவும் அல்லது CM/L எண்ணை உள்ளிடவும்",
    qa_check_mark: "BIS முத்திரையைச் சரிபார்க்கவும்",
    qa_check_mark_desc: "ISI, CRS R-எண் அல்லது ஹால்மார்க்கைச் சரிபார்க்கவும்",
    qa_cert_help: "சான்றிதழ் உதவி",
    qa_cert_help_desc: "MSME 6-படி இணக்க வழிகாட்டி",
    qa_find_lab: "ஆய்வகத்தைக் கண்டறியவும்",
    qa_find_lab_desc: "BIS அங்கீகாரம் பெற்ற NABL சோதனை ஆய்வகங்கள்",
    qa_report_complaint: "புகார் பதிவு செய்யவும்",
    qa_report_complaint_desc: "BIS சட்டம் 2016 இன் கீழ் புகார் ஆவணத்தை உருவாக்கவும்",
    diff_badge: "நீதிபதிகள் மதிப்பீட்டு காட்சி",
    diff_title: "டாக்லிங் + BGE-M3 சொற்பொருள் மாற்றக் கண்டறிதல் (பூஜ்ஜிய ஹாஷிங்)",
    diff_desc: "நீதிபதிகளின் தேவைகளுக்கு ஏற்ப பிரிவு வாரியான பதிப்பு மற்றும் ஒழுங்குமுறை தாக்க பகுப்பாய்வு.",
    diff_demo1: "IS 2347:2017 பிரிவு 5.2 (மாற்றப்பட்டது)",
    diff_demo2: "IS 17803:2022 (புதிய பிரிவு சேர்க்கப்பட்டது)",
    diff_demo3: "IS 13252:2010 (மறுபெயரிடப்பட்ட பிரிவு)",
    assistant_welcome: "வணக்கம்! நான் நெக்ஸாமாதிரி, இந்தியத் தரநிலைகள் மற்றும் BIS சேவைகளுக்கான உங்கள் AI உதவியாளர். எந்தவொரு தயாரிப்பு, தரம் அல்லது அரசாணை பற்றியும் கேட்டு சரிபார்க்கப்பட்ட வழிகாட்டுதலைப் பெறுங்கள்.",
    tab_consumer: "🛒 நுகர்வோர் முத்திரை சரிபார்ப்பு",
    tab_startup: "🚀 ஸ்டார்ட்அப் / MSME 14-படி வழிகாட்டி",
    tab_builder: "🏭 தயாரிப்பாளர் தொழில்நுட்ப விவரக்குறிப்புகள்",
    glossary_btn: "இந்த BIS சொல்லின் பொருள் என்ன?",
    input_placeholder: "ஏதேனும் தரநிலை, QCO அல்லது தயாரிப்பு பற்றி கேளுங்கள்...",
    send_btn: "கேளுங்கள்",
    listening: "கேட்கிறது... இப்போது பேசுங்கள்",
    source_locked: "மூலம் உறுதிப்படுத்தப்பட்டது",
    unverified: "சரிபார்க்கப்படாதது"
  },

  te: {
    gov_india: "భారత ప్రభుత్వం",
    bis_title: "భారతీయ ప్రమాణాల బ్యూరో (BIS)",
    demo_prototype: "డెమో ప్రోటోటైప్",
    manakonline: "మానక్ ఆన్‌లైన్",
    app_title: "నెక్సాస్టాండర్డ్స్",
    app_badge: "SIH26107 సహాయకుడు",
    app_subtitle: "భారతీయ ప్రమాణాలు మరియు నిబంధనల కోసం విశ్వసనీయమైన మరియు ఖచ్చితమైన మద్దతు.",
    nav_assistant: "AI సహాయకుడు",
    nav_verify: "ఉత్పత్తి ధృవీకరణ",
    nav_standards: "ప్రమాణాలు & QCO",
    nav_compliance: "నియంత్రణ రోడ్‌మ్యాప్",
    nav_labs: "పరీక్షా ప్రయోగశాలలు",
    nav_hallmarking: "హాల్‌మార్కింగ్",
    nav_grievance: "వినియోగదారుల ఫిర్యాదు",
    nav_admin: "అడ్మిన్ పోర్టల్",
    side_group1: "1. ఒకే చోట అడగండి",
    side_group2: "2. BIS నిబంధనలను అర్థం చేసుకోండి",
    side_group3: "3. వేగవంతమైన ఉత్పత్తి ధృవీకరణ",
    side_group4: "4. తదుపరి చర్య తీసుకోండి",
    side_group5: "5. శాసనబద్ధ రిజిస్ట్రీ",
    side_assistant: "AI సంభాషణ సహాయకుడు",
    side_standards: "ప్రమాణాలు & QCO అన్వేషకుడు",
    side_compare: "ప్రమాణాల పోలిక మ్యాట్రిక్స్",
    side_certification: "ధృవీకరణ పథకాలు",
    side_testing: "పరీక్షా అవసరాలు",
    side_verify: "ఉత్పత్తి ధృవీకరణ (OCR)",
    side_hallmarking: "బంగారు హాల్‌మార్కింగ్ & HUID",
    side_compliance: "నియంత్రణ రోడ్‌మ్యాప్",
    side_labs: "ప్రయోగశాల మ్యాచింగ్",
    side_grievance: "BIS ఫిర్యాదు సహాయకుడు",
    side_profile: "యూజర్ ప్రొఫైల్",
    side_settings: "సెట్టింగ్‌లు & LLM",
    side_admin_rag: "నాలెడ్జ్ స్పెక్స్ & RAG",
    side_admin_docs: "పత్రాల రిజిస్ట్రీ",
    hero_title: "మీ దగ్గర ఏ ఉత్పత్తి ఉంది లేదా మీరు దేనిని తయారు చేయాలనుకుంటున్నారో చెప్పండి.",
    hero_subtitle: "సంక్లిష్టమైన BIS నిబంధనలు, భారతీయ ప్రమాణాలు మరియు గెజిట్ QCOలను మీ పాత్రకు అనుగుణంగా సరళమైన మార్గదర్శకంగా మారుస్తుంది.",
    persona_consumer_title: "నేను ఒక వినియోగదారుడిని",
    persona_consumer_desc: "ఉత్పత్తి, BIS గుర్తు, లైసెన్స్ లేదా అవసరాన్ని తనిఖీ చేయండి",
    persona_consumer_action: "గుర్తు & ప్యాకేజింగ్ ధృవీకరించండి →",
    persona_consumer_badge: "సరళమైన భాష",
    persona_startup_title: "నేను ఒక స్టార్టప్ / MSME",
    persona_startup_desc: "ఈ ఉత్పత్తిని తయారు చేయడానికి లేదా విక్రయించడానికి నాకు ఏమి కావాలో తెలుసుకోండి",
    persona_startup_action: "స్టార్టప్ తయారీ గైడ్ →",
    persona_startup_badge: "14-దశల చెక్‌లిస్ట్",
    persona_builder_title: "నేను ఒక తయారీదారుని / ఇంజనీర్‌ని",
    persona_builder_desc: "ప్రమాణాలు, పరీక్షలు, పత్రాలు మరియు ధృవీకరణ అవసరాలను పొందండి",
    persona_builder_action: "నిబంధనలు & పరీక్ష పారామితులు →",
    persona_builder_badge: "ఇంజనీరింగ్ వివరాలు",
    search_role_prefix: "నియంత్రణ సమాచారాన్ని శోధించండి (క్రియాశీల పాత్ర: ",
    search_role_suffix: ")",
    switch_role: "పాత్రను మార్చండి:",
    role_consumer: "వినియోగదారుడు",
    role_startup: "స్టార్టప్",
    role_builder: "ఇంజనీర్",
    search_placeholder: "ఉదా. 'మొబైల్', 'ప్రెషర్ కుక్కర్‌కు ఏ ప్రమాణం వర్తిస్తుంది?'...",
    search_button: "సమాచారాన్ని శోధించండి →",
    try_scenarios: "త్వరిత ఉదాహరణలను ప్రయత్నించండి:",
    verify_photo_button: "గుర్తు / ఫోటోను ధృవీకరించండి",
    qa_title: "త్వరిత చర్యలు",
    qa_search_std: "ప్రమాణాలను శోధించండి",
    qa_search_std_desc: "వర్తించే IS నిబంధనలను అన్వేషించండి",
    qa_verify_prod: "ఉత్పత్తిని ధృవీకరించండి",
    qa_verify_prod_desc: "లేబుల్‌ను స్కాన్ చేయండి లేదా CM/L నంబర్‌ను నమోదు చేయండి",
    qa_check_mark: "BIS గుర్తును తనిఖీ చేయండి",
    qa_check_mark_desc: "ISI మార్క్, CRS R-నంబర్ లేదా హాల్‌మార్క్‌ను ధృవీకరించండి",
    qa_cert_help: "ధృవీకరణ సహాయం",
    qa_cert_help_desc: "MSME 6-దశల రోడ్‌మ్యాప్",
    qa_find_lab: "ప్రయోగశాలను కనుగొనండి",
    qa_find_lab_desc: "BIS గుర్తింపు పొందిన NABL పరీక్షా ల్యాబ్‌లు",
    qa_report_complaint: "ఫిర్యాదు చేయండి",
    qa_report_complaint_desc: "BIS చట్టం 2016 ప్రకారం ఫిర్యాదు పత్రాన్ని రూపొందించండి",
    diff_badge: "న్యాయనిర్ణేతల బెంచ్‌మార్క్ ప్రదర్శన",
    diff_title: "డాక్లింగ్ + BGE-M3 సెమాంటిక్ మార్పు గుర్తింపు (జీరో హ్యాషింగ్)",
    diff_desc: "క్లాజ్ వారీగా డాక్యుమెంట్ వెర్షనింగ్ మరియు ప్రభావ విశ్లేషణ.",
    diff_demo1: "IS 2347:2017 క్లాజ్ 5.2 (సవరించబడింది)",
    diff_demo2: "IS 17803:2022 (కొత్త క్లాజ్ జోడించబడింది)",
    diff_demo3: "IS 13252:2010 (పేరు మార్చబడిన క్లాజ్)",
    assistant_welcome: "నమస్కారం! నేను నెక్సాస్టాండర్డ్స్, భారతీయ ప్రమాణాలు మరియు BIS సేవల కోసం మీ AI సహాయకుడిని. ఏదైనా ఉత్పత్తి, ప్రమాణం లేదా గెజిట్ ఉత్తర్వుల గురించి అడగండి.",
    tab_consumer: "🛒 వినియోగదారు మార్క్ ధృవీకరణ",
    tab_startup: "🚀 స్టార్టప్ / MSME 14-దశల రోడ్‌మ్యాప్",
    tab_builder: "🏭 ఇంజనీరింగ్ స్పెసిఫికేషన్‌లు",
    glossary_btn: "ఈ BIS పదం అర్థం ఏమిటి?",
    input_placeholder: "ఏదైనా ప్రమాణం లేదా ఉత్పత్తి గురించి అడగండి...",
    send_btn: "అడగండి",
    listening: "వింటోంది... మాట్లాడండి",
    source_locked: "మూలం ధృవీకరించబడింది",
    unverified: "ధృవీకరించబడలేదు"
  },

  mr: {
    gov_india: "भारत सरकार",
    bis_title: "भारतीय मानक ब्युरो (BIS)",
    demo_prototype: "डेमो प्रोटोटाइप",
    manakonline: "मानकऑनलाइन",
    app_title: "नेक्सामानक",
    app_badge: "SIH26107 सहाय्यक",
    app_subtitle: "भारतीय मानके आणि नियमांसाठी विश्वसनीय आणि अचूक अनुपालन समर्थन.",
    nav_assistant: "AI सहाय्यक",
    nav_verify: "उत्पादन पडताळणी",
    nav_standards: "मानके आणि QCO",
    nav_compliance: "अनुपालन रोडमॅप",
    nav_labs: "चाचणी प्रयोगशाळा",
    nav_hallmarking: "हॉलमार्किंग",
    nav_grievance: "ग्राहक तक्रार",
    nav_admin: "प्रशासक पोर्टल",
    side_group1: "1. एकाच ठिकाणी विचारा",
    side_group2: "2. BIS नियम समजून घ्या",
    side_group3: "3. जलद उत्पादन पडताळणी",
    side_group4: "4. पुढील पाऊल उचला",
    side_group5: "5. प्रशासकीय नोंदणी",
    side_assistant: "AI संभाषण सहाय्यक",
    side_standards: "मानके आणि QCO शोध",
    side_compare: "मानक तुलना मॅट्रिक्स",
    side_certification: "प्रमाणीकरण योजना",
    side_testing: "चाचणी आवश्यकता",
    side_verify: "उत्पादन पडताळणी (OCR)",
    side_hallmarking: "सुवर्ण हॉलमार्किंग आणि HUID",
    side_compliance: "अनुपालन रोडमॅप",
    side_labs: "प्रयोगशाळा जुळणी",
    side_grievance: "BIS तक्रार सहाय्यक",
    side_profile: "वापरकर्ता प्रोफाइल",
    side_settings: "सेटिंग्ज आणि LLM",
    side_admin_rag: "ज्ञान तपशील आणि RAG",
    side_admin_docs: "दस्तऐवज नोंदणी",
    hero_title: "तुमच्याकडे कोणते उत्पादन आहे किंवा तुम्हाला काय बनवायचे आहे ते सांगा.",
    hero_subtitle: "नेक्सामानक गुंतागुंतीच्या BIS कायदेशीर नियमांचे तुमच्या भूमिकेनुसार सोप्या मार्गदर्शनात रूपांतर करते.",
    persona_consumer_title: "मी एक ग्राहक आहे",
    persona_consumer_desc: "उत्पादन, BIS चिन्ह, परवाना किंवा आवश्यकता तपासा",
    persona_consumer_action: "चिन्ह आणि पॅकेजिंग तपासा →",
    persona_consumer_badge: "सोपी भाषा",
    persona_startup_title: "मी एक स्टार्टअप / MSME आहे",
    persona_startup_desc: "हे उत्पादन बनवण्यासाठी किंवा विकण्यासाठी मला काय आवश्यक आहे ते जाणून घ्या",
    persona_startup_action: "स्टार्टअप उत्पादन मार्गदर्शक →",
    persona_startup_badge: "14-टप्प्यांची चेकलिस्ट",
    persona_builder_title: "मी एक उत्पादन निर्माता / अभियंता आहे",
    persona_builder_desc: "मानके, चाचण्या, कागदपत्रे आणि प्रमाणन आवश्यकता मिळवा",
    persona_builder_action: "कलमे आणि चाचणी मापदंड →",
    persona_builder_badge: "अभियांत्रिकी तपशील",
    search_role_prefix: "नियामक माहिती शोधा (सक्रिय भूमिका: ",
    search_role_suffix: ")",
    switch_role: "भूमिका बदला:",
    role_consumer: "ग्राहक",
    role_startup: "स्टार्टअप",
    role_builder: "अभियंता",
    search_placeholder: "उदा. 'मोबाइल', 'प्रेशर कुकरला कोणते मानक लागू होते?'...",
    search_button: "माहिती शोधा →",
    try_scenarios: "त्वरित उदाहरणे पहा:",
    verify_photo_button: "चिन्ह / फोटो तपासा",
    qa_title: "जलद कृती",
    qa_search_std: "मानके शोधा",
    qa_search_std_desc: "लागू IS तपशील एक्सप्लोर करा",
    qa_verify_prod: "उत्पादन पडताळा",
    qa_verify_prod_desc: "लेबल स्कॅन करा किंवा CM/L क्रमांक प्रविष्ट करा",
    qa_check_mark: "BIS चिन्ह तपासा",
    qa_check_mark_desc: "ISI मार्क, CRS R-नंबर किंवा हॉलमार्क तपासा",
    qa_cert_help: "प्रमाणन मदत",
    qa_cert_help_desc: "MSME 6-टप्प्यांचा रोडमॅप",
    qa_find_lab: "प्रयोगशाळा शोधा",
    qa_find_lab_desc: "BIS-मान्यताप्राप्त NABL चाचणी लॅब",
    qa_report_complaint: "तक्रार नोंदवा",
    qa_report_complaint_desc: "BIS कायदा 2016 अंतर्गत तक्रार मसुदा तयार करा",
    diff_badge: "न्यायाधीश बेंचमार्क प्रात्यक्षिक",
    diff_title: "डॉकलिंग + BGE-M3 सिमेंटिक बदल शोध (झिरो हॅशिंग)",
    diff_desc: "कलमनिहाय दस्तऐवज आवृत्ती आणि नियामक प्रभाव विश्लेषण.",
    diff_demo1: "IS 2347:2017 कलम 5.2 (सुधारित)",
    diff_demo2: "IS 17803:2022 (नवीन कलम जोडले)",
    diff_demo3: "IS 13252:2010 (पुनःक्रमांकित कलम)",
    assistant_welcome: "नमस्ते! मी नेक्सामानक आहे, भारतीय मानके आणि BIS सेवांसाठी तुमचा AI सहाय्यक. कोणत्याही उत्पादनाविषयी विचारा.",
    tab_consumer: "🛒 ग्राहक चिन्ह पडताळणी",
    tab_startup: "🚀 स्टार्टअप 14-टप्प्यांचा रोडमॅप",
    tab_builder: "🏭 तांत्रिक तपशील",
    glossary_btn: "या BIS संज्ञेचा अर्थ काय आहे?",
    input_placeholder: "कोणत्याही मानकाविषयी किंवा उत्पादनाविषयी विचारा...",
    send_btn: "विचारा",
    listening: "ऐकत आहे... बोला",
    source_locked: "स्रोत-सत्यापित",
    unverified: "असत्यापित"
  },

  bn: {
    gov_india: "ভারত সরকার",
    bis_title: "ব্যুরো অফ ইন্ডিয়ান স্ট্যান্ডার্ডস (BIS)",
    demo_prototype: "ডেমো প্রোটোটাইপ",
    manakonline: "মানকঅনলাইন",
    app_title: "নেক্সাস্ট্যান্ডার্ডস",
    app_badge: "SIH26107 সহকারী",
    app_subtitle: "ভারতীয় মান এবং বিধিমালার জন্য বিশ্বস্ত ও সঠিক সম্মতি সহায়তা।",
    nav_assistant: "AI সহকারী",
    nav_verify: "পণ্য যাচাইকরণ",
    nav_standards: "মানক ও QCO",
    nav_compliance: "সম্মতি রোডম্যাপ",
    nav_labs: "পরীক্ষাগার",
    nav_hallmarking: "হলমার্কিং",
    nav_grievance: "ভোক্তা অভিযোগ",
    nav_admin: "অ্যাডমিন পোর্টাল",
    side_group1: "১. এক জায়গায় জিজ্ঞাসা করুন",
    side_group2: "২. BIS নিয়মাবলী বুঝুন",
    side_group3: "৩. দ্রুত পণ্য যাচাইকরণ",
    side_group4: "৪. পরবর্তী পদক্ষেপ নিন",
    side_group5: "৫. প্রশাসনিক রেজিস্ট্রি",
    side_assistant: "AI কথোপকথন সহকারী",
    side_standards: "মানক ও QCO এক্সপ্লোরার",
    side_compare: "মানক তুলনা ম্যাট্রিক্স",
    side_certification: "শংসাপত্র প্রকল্পসমূহ",
    side_testing: "পরীক্ষার প্রয়োজনীয়তা",
    side_verify: "পণ্য যাচাইকরণ (OCR)",
    side_hallmarking: "স্বর্ণ হলমার্কিং ও HUID",
    side_compliance: "সম্মতি রোডম্যাপ",
    side_labs: "ল্যাব ম্যাচিং",
    side_grievance: "BIS অভিযোগ সহকারী",
    side_profile: "ব্যবহারকারী প্রোফাইল",
    side_settings: "সেটিংস ও LLM",
    side_admin_rag: "জ্ঞান স্পেসিফিকেশন ও RAG",
    side_admin_docs: "নথিপত্র রেজিস্ট্রি",
    hero_title: "আপনার কাছে কী পণ্য আছে বা আপনি কী তৈরি করতে চান তা জানান।",
    hero_subtitle: "নেক্সাস্ট্যান্ডার্ডস জটিল BIS নিয়মাবলী এবং ভারতীয় মানকে আপনার ভূমিকার জন্য সহজ নির্দেশিকায় রূপান্তরিত করে।",
    persona_consumer_title: "আমি একজন ভোক্তা",
    persona_consumer_desc: "একটি পণ্য, BIS চিহ্ন বা লাইসেন্স যাচাই করুন",
    persona_consumer_action: "চিহ্ন ও প্যাকেজিং যাচাই করুন →",
    persona_consumer_badge: "সহজ ভাষা",
    persona_startup_title: "আমি একটি স্টার্টআপ / MSME",
    persona_startup_desc: "এই পণ্য তৈরি বা বিক্রি করার জন্য আমার কী প্রয়োজন তা জানুন",
    persona_startup_action: "স্টার্টআপ উত্পাদন গাইড →",
    persona_startup_badge: "১৪-ধাপের চেকলিস্ট",
    persona_builder_title: "আমি একজন পণ্য নির্মাতা / প্রকৌশলী",
    persona_builder_desc: "মানক, পরীক্ষা এবং শংসাপত্রের প্রয়োজনীয়তা পান",
    persona_builder_action: "ধারা ও পরীক্ষার পরামিতি →",
    persona_builder_badge: "প্রকৌশল স্পেসিফিকেশন",
    search_role_prefix: "নিয়ন্ত্রক তথ্য অনুসন্ধান করুন (সক্রিয় ভূমিকা: ",
    search_role_suffix: ")",
    switch_role: "ভূমিকা পরিবর্তন করুন:",
    role_consumer: "ভোক্তা",
    role_startup: "স্টার্টআপ",
    role_builder: "প্রকৌশলী",
    search_placeholder: "যেমন 'মোবাইল', 'প্রেসার কুকারে কোন মান প্রযোজ্য?'...",
    search_button: "তথ্য অনুসন্ধান করুন →",
    try_scenarios: "উদাহরণগুলি চেষ্টা করুন:",
    verify_photo_button: "চিহ্ন / ছবি যাচাই করুন",
    qa_title: "দ্রুত পদক্ষেপ",
    qa_search_std: "মানক অনুসন্ধান করুন",
    qa_search_std_desc: "প্রযোজ্য IS স্পেসিফিকেশন অন্বেষণ করুন",
    qa_verify_prod: "পণ্য যাচাই করুন",
    qa_verify_prod_desc: "লেবেল স্ক্যান করুন বা CM/L নম্বর লিখুন",
    qa_check_mark: "BIS চিহ্ন পরীক্ষা করুন",
    qa_check_mark_desc: "ISI মার্ক, CRS R-নম্বর বা হলমার্ক যাচাই করুন",
    qa_cert_help: "শংসাপত্র সহায়তা",
    qa_cert_help_desc: "MSME ৬-ধাপের সম্মতি রোডম্যাপ",
    qa_find_lab: "ল্যাব খুঁজুন",
    qa_find_lab_desc: "BIS-স্বীকৃত NABL পরীক্ষাগার",
    qa_report_complaint: "অভিযোগ দায়ের করুন",
    qa_report_complaint_desc: "BIS আইন ২০১৬ এর অধীনে অভিযোগ নথি প্রস্তুত করুন",
    diff_badge: "বিচারকদের বেঞ্চমার্ক প্রদর্শনী",
    diff_title: "ডক্লিং + BGE-M3 শব্দার্থিক পরিবর্তন সনাক্তকরণ (শূন্য হ্যাশিং)",
    diff_desc: "ধারা অনুসারে নথি সংস্করণ এবং নিয়ন্ত্রক প্রভাব বিশ্লেষণ।",
    diff_demo1: "IS 2347:2017 ধারা ৫.২ (সংশোধিত)",
    diff_demo2: "IS 17803:2022 (নতুন ধারা যুক্ত)",
    diff_demo3: "IS 13252:2010 (পুনরায় সংখ্যাযুক্ত ধারা)",
    assistant_welcome: "নমস্কার! আমি নেক্সাস্ট্যান্ডার্ডস, ভারতীয় মান এবং BIS পরিষেবার জন্য আপনার AI সহকারী। যে কোনো পণ্য সম্পর্কে জিজ্ঞাসা করুন।",
    tab_consumer: "🛒 ভোক্তা চিহ্ন যাচাইকরণ",
    tab_startup: "🚀 স্টার্টআপ ১৪-ধাপের রোডম্যাপ",
    tab_builder: "🏭 প্রযুক্তিগত স্পেসিফিকেশন",
    glossary_btn: "এই BIS শব্দের অর্থ কী?",
    input_placeholder: "যে কোনো মান বা পণ্য সম্পর্কে জিজ্ঞাসা করুন...",
    send_btn: "জিজ্ঞাসা করুন",
    listening: "শুনছি... এখন বলুন",
    source_locked: "উত্স-যাচাইকৃত",
    unverified: "অযাচাইকৃত"
  },

  ml: {
    gov_india: "ഭാരത സർക്കാർ",
    bis_title: "ബ്യൂറോ ഓഫ് ഇന്ത്യൻ സ്റ്റാൻഡേർഡ്സ് (BIS)",
    demo_prototype: "ഡെമോ പ്രോട്ടോടൈപ്പ്",
    manakonline: "മാനക്ഓൺലൈൻ",
    app_title: "നെക്സാസ്റ്റാൻഡേർഡ്സ്",
    app_badge: "SIH26107 അസിസ്റ്റന്റ്",
    app_subtitle: "ഇന്ത്യൻ മാനദണ്ഡങ്ങൾക്കും ചട്ടങ്ങൾക്കുമുള്ള വിശ്വസനീയമായ അനുസരണ പിന്തുണ.",
    nav_assistant: "AI അസിസ്റ്റന്റ്",
    nav_verify: "ഉൽപ്പന്ന പരിശോധന",
    nav_standards: "മാനദണ്ഡങ്ങൾ & QCO",
    nav_compliance: "പാലിക്കൽ മാർഗ്ഗരേഖ",
    nav_labs: "ടെസ്റ്റിംഗ് ലാബുകൾ",
    nav_hallmarking: "ഹാൾമാർക്കിംഗ്",
    nav_grievance: "ഉപഭോക്തൃ പരാതി",
    nav_admin: "അഡ്മിൻ പോർട്ടൽ",
    side_group1: "1. ഒരിടത്ത് ചോദിക്കൂ",
    side_group2: "2. BIS നിയമങ്ങൾ മനസ്സിലാക്കൂ",
    side_group3: "3. വേഗത്തിലുള്ള പരിശോധന",
    side_group4: "4. അടുത്ത നടപടി സ്വീകരിക്കൂ",
    side_group5: "5. ഔദ്യോഗിക രജിസ്ട്രി",
    side_assistant: "AI സംഭാഷണ അസിസ്റ്റന്റ്",
    side_standards: "മാനദണ്ഡങ്ങൾ & QCO എക്സ്പ്ലോറർ",
    side_compare: "താരതമ്യ പട്ടിക",
    side_certification: "സർട്ടിഫിക്കേഷൻ സ്കീമുകൾ",
    side_testing: "ടെസ്റ്റിംഗ് ആവശ്യകതകൾ",
    side_verify: "ഉൽപ്പന്ന പരിശോധന (OCR)",
    side_hallmarking: "ഗോൾഡ് ഹാൾമാർക്കിംഗ് & HUID",
    side_compliance: "പാലിക്കൽ മാർഗ്ഗരേഖ",
    side_labs: "ലാബ് മാച്ചിംഗ്",
    side_grievance: "BIS പരാതി അസിസ്റ്റന്റ്",
    side_profile: "യൂസർ പ്രൊഫൈൽ",
    side_settings: "ക്രമീകരണങ്ങൾ & LLM",
    side_admin_rag: "വിവരങ്ങൾ & RAG",
    side_admin_docs: "രേഖകളുടെ രജിസ്ട്രി",
    hero_title: "നിങ്ങളുടെ പക്കൽ ഏത് ഉൽപ്പന്നമുണ്ടെന്നോ എന്താണ് നിർമ്മിക്കാൻ ആഗ്രഹിക്കുന്നതെന്നോ പറയൂ.",
    hero_subtitle: "സങ്കീർണ്ണമായ BIS നിയന്ത്രണങ്ങളെ നിങ്ങളുടെ പങ്കിന് അനുസൃതമായ ലളിതമായ മാർഗ്ഗനിർദ്ദേശങ്ങളാക്കി മാറ്റുന്നു.",
    persona_consumer_title: "ഞാൻ ഒരു ഉപഭോക്താവാണ്",
    persona_consumer_desc: "ഒരു ഉൽപ്പന്നം, BIS ചിഹ്നം അല്ലെങ്കിൽ ലൈസൻസ് പരിശോധിക്കുക",
    persona_consumer_action: "ചിഹ്നവും പാക്കേജിംഗും പരിശോധിക്കുക →",
    persona_consumer_badge: "ലളിതമായ ഭാഷ",
    persona_startup_title: "ഞാൻ ഒരു സ്റ്റാർട്ടപ്പ് / MSME ആണ്",
    persona_startup_desc: "ഈ ഉൽപ്പന്നം നിർമ്മിക്കാനോ വിൽക്കാനോ എനിക്ക് എന്താണ് വേണ്ടതെന്ന് അറിയുക",
    persona_startup_action: "സ്റ്റാർട്ടപ്പ് നിർമ്മാണ ഗൈഡ് →",
    persona_startup_badge: "14-ഘട്ട ചെക്ക്‌ലിസ്റ്റ്",
    persona_builder_title: "ഞാൻ ഒരു നിർമ്മാതാവ് / എഞ്ചിനീയറാണ്",
    persona_builder_desc: "മാനദണ്ഡങ്ങൾ, പരിശോധനകൾ, സർട്ടിഫിക്കേഷൻ ആവശ്യകതകൾ എന്നിവ നേടുക",
    persona_builder_action: "വ്യവസ്ഥകളും ടെസ്റ്റിംഗ് പാരാമീറ്ററുകളും →",
    persona_builder_badge: "എഞ്ചിനീയറിംഗ് വിവരങ്ങൾ",
    search_role_prefix: "നിയന്ത്രണ വിവരങ്ങൾ തിരയുക (സജീവ പങ്ക്: ",
    search_role_suffix: ")",
    switch_role: "പങ്ക് മാറ്റുക:",
    role_consumer: "ഉപഭോക്താവ്",
    role_startup: "സ്റ്റാർട്ടപ്പ്",
    role_builder: "എഞ്ചിനീയർ",
    search_placeholder: "ഉദാ: 'മൊബൈൽ', 'പ്രഷർ കുക്കറിന് ഏത് മാനദണ്ഡമാണ് ബാധകം?'...",
    search_button: "വിവരങ്ങൾ തിരയുക →",
    try_scenarios: "വേഗത്തിലുള്ള ഉദാഹരണങ്ങൾ:",
    verify_photo_button: "ചിഹ്നം / ഫോട്ടോ പരിശോധിക്കുക",
    qa_title: "ദ്രുത നടപടികൾ",
    qa_search_std: "മാനദണ്ഡങ്ങൾ തിരയുക",
    qa_search_std_desc: "ബാധകമായ IS മാനദണ്ഡങ്ങൾ കണ്ടെത്തുക",
    qa_verify_prod: "ഉൽപ്പന്നം പരിശോധിക്കുക",
    qa_verify_prod_desc: "ലേബൽ സ്കാൻ ചെയ്യുക അല്ലെങ്കിൽ CM/L നമ്പർ നൽകുക",
    qa_check_mark: "BIS ചിഹ്നം പരിശോധിക്കുക",
    qa_check_mark_desc: "ISI മാർക്ക്, CRS R-നമ്പർ അല്ലെങ്കിൽ ഹാൾമാർക്ക് പരിശോധിക്കുക",
    qa_cert_help: "സർട്ടിഫിക്കേഷൻ സഹായം",
    qa_cert_help_desc: "MSME 6-ഘട്ട മാർഗ്ഗരേഖ",
    qa_find_lab: "ലാബ് കണ്ടെത്തുക",
    qa_find_lab_desc: "BIS അംഗീകൃത NABL ലാബുകൾ",
    qa_report_complaint: "പരാതി നൽകുക",
    qa_report_complaint_desc: "BIS ആക്ട് 2016 പ്രകാരം പരാതി ഫയൽ ചെയ്യുക",
    diff_badge: "ജഡ്ജസ് ബെഞ്ച്മാർക്ക് പ്രദർശനം",
    diff_title: "ഡോക്ലിംഗ് + BGE-M3 അർത്ഥപരമായ മാറ്റങ്ങൾ കണ്ടെത്തൽ (സീറോ ഹാഷിംഗ്)",
    diff_desc: "ഡോക്യുമെന്റ് പതിപ്പുകളും സ്വാധീന വിശകലനവും.",
    diff_demo1: "IS 2347:2017 വ്യവസ്ഥ 5.2 (പരിഷ്കരിച്ചത്)",
    diff_demo2: "IS 17803:2022 (പുതിയ വ്യവസ്ഥ ചേർത്തു)",
    diff_demo3: "IS 13252:2010 (പേരുമാറ്റിയ വ്യവസ്ഥ)",
    assistant_welcome: "നമസ്കാരം! ഞാൻ നെക്സാസ്റ്റാൻഡേർഡ്സ്, ഇന്ത്യൻ മാനദണ്ഡങ്ങൾക്കും BIS സേവനങ്ങൾക്കുമുള്ള നിങ്ങളുടെ AI അസിസ്റ്റന്റാണ്. ഏത് ഉൽപ്പന്നത്തെക്കുറിച്ചും ചോദിക്കൂ.",
    tab_consumer: "🛒 ഉപഭോക്തൃ മാർക്ക് പരിശോധന",
    tab_startup: "🚀 സ്റ്റാർട്ടപ്പ് 14-ഘട്ട മാർഗ്ഗരേഖ",
    tab_builder: "🏭 സാങ്കേതിക വിവരങ്ങൾ",
    glossary_btn: "ഈ BIS പദത്തിന്റെ അർത്ഥമെന്താണ്?",
    input_placeholder: "ഏതെങ്കിലും മാനദണ്ഡത്തെക്കുറിച്ചോ ഉൽപ്പന്നത്തെക്കുറിച്ചോ ചോദിക്കൂ...",
    send_btn: "ചോദിക്കൂ",
    listening: "കേൾക്കുന്നു... സംസാരിക്കൂ",
    source_locked: "ഉറവിടം സ്ഥിരീകരിച്ചു",
    unverified: "സ്ഥിരീകരിക്കാത്തത്"
  },

  gu: {
    gov_india: "ભારત સરકાર",
    bis_title: "બ્યુરો ઓફ ઇન્ડિયન સ્ટાન્ડર્ડ્સ (BIS)",
    demo_prototype: "ડેમો પ્રોટોટાઇપ",
    manakonline: "માનકઓનલાઇન",
    app_title: "નેક્સhumanસ્ટાન્ડર્ડ્સ",
    app_badge: "SIH26107 સહાયક",
    app_subtitle: "ભારતીય ધોરણો અને નિયમો માટે વિશ્વસનીય અને સચોટ અનુપાલન સમર્થન.",
    nav_assistant: "AI સહાયક",
    nav_verify: "ઉત્પાદન ચકાસણી",
    nav_standards: "ધોરણો અને QCO",
    nav_compliance: "અનુપાલન રોડમેપ",
    nav_labs: "પરીક્ષણ પ્રયોગશાળાઓ",
    nav_hallmarking: "હોલમાર્કિંગ",
    nav_grievance: "ગ્રાહક ફરિયાદ",
    nav_admin: "એડમિન પોર્ટલ",
    side_group1: "1. એક જ જગ્યાએ પૂછો",
    side_group2: "2. BIS નિયમો સમજો",
    side_group3: "3. ઝડપી ઉત્પાદન ચકાસણી",
    side_group4: "4. આગળનું પગલું ભરો",
    side_group5: "5. સત્તાવાર રજિસ્ટ્રી",
    side_assistant: "AI સંવાદાત્મક સહાયક",
    side_standards: "ધોરણો અને QCO એક્સપ્લોરર",
    side_compare: "ધોરણ સરખામણી મેટ્રિક્સ",
    side_certification: "પ્રમાણીકરણ યોજનાઓ",
    side_testing: "પરીક્ષણ આવશ્યકતાઓ",
    side_verify: "ઉત્પાદન ચકાસણી (OCR)",
    side_hallmarking: "સુવર્ણ હોલમાર્કિંગ અને HUID",
    side_compliance: "અનુપાલન રોડમેપ",
    side_labs: "પ્રયોગશાળા મેળવણી",
    side_grievance: "BIS ફરિયાદ સહાયક",
    side_profile: "વપરાશકર્તા પ્રોફાઇલ",
    side_settings: "સેટિંગ્સ અને LLM",
    side_admin_rag: "જ્ઞાન વિશિષ્ટતાઓ અને RAG",
    side_admin_docs: "દસ્તાવેજ રજિસ્ટ્રી",
    hero_title: "જણાવો કે તમારી પાસે કયું ઉત્પાદન છે અથવા તમે શું બનાવવા માંગો છો.",
    hero_subtitle: "નેક્સhumanસ્ટાન્ડર્ડ્સ જટિલ BIS વૈધાનિક નિયમો અને ભારતીય ધોરણોને તમારી ભૂમિકા અનુસાર સરળ માર્ગદર્શનમાં રૂપાંતરિત કરે છે.",
    persona_consumer_title: "હું એક ગ્રાહક છું",
    persona_consumer_desc: "ઉત્પાદન, BIS ચિહ્ન, લાઇસન્સ અથવા આવશ્યકતા તપાસો",
    persona_consumer_action: "માર્ક અને પેકેજિંગ ચકાસો →",
    persona_consumer_badge: "સરળ ભાષા",
    persona_startup_title: "હું એક સ્ટાર્ટઅપ / MSME છું",
    persona_startup_desc: "આ ઉત્પાદન બનાવવા અથવા વેચવા માટે મારે શું જોઈએ છે તે જાણો",
    persona_startup_action: "સ્ટાર્ટઅપ ઉત્પાદન માર્ગદર્શિકા →",
    persona_startup_badge: "14-પગલાની ચેકલિસ્ટ",
    persona_builder_title: "હું એક ઉત્પાદન નિર્માતા / એન્જિનિયર છું",
    persona_builder_desc: "ધોરણો, પરીક્ષણો અને પ્રમાણીકરણ આવશ્યકતાઓ મેળવો",
    persona_builder_action: "કલમો અને પરીક્ષણ પરિમાણો →",
    persona_builder_badge: "એન્જિનિયરિંગ વિગતો",
    search_role_prefix: "નિયમનકારી માહિતી શોધો (સક્રિય ભૂમિકા: ",
    search_role_suffix: ")",
    switch_role: "ભૂમિકા બદલો:",
    role_consumer: "ગ્રાહક",
    role_startup: "સ્ટાર્ટઅપ",
    role_builder: "એન્જિનિયર",
    search_placeholder: "દા.ત. 'મોબાઇલ', 'પ્રેશર કૂકર પર કયું ધોરણ લાગુ પડે છે?'...",
    search_button: "માહિતી શોધો →",
    try_scenarios: "ઝડપી ઉદાહરણો જુઓ:",
    verify_photo_button: "ચિહ્ન / ફોટો ચકાસો",
    qa_title: "ઝડપી પગલાં",
    qa_search_std: "ધોરણો શોધો",
    qa_search_std_desc: "લાગુ IS વિશિષ્ટતાઓ જુઓ",
    qa_verify_prod: "ઉત્પાદન ચકાસો",
    qa_verify_prod_desc: "લેબલ સ્કેન કરો અથવા CM/L નંબર દાખલ કરો",
    qa_check_mark: "BIS ચિહ્ન તપાસો",
    qa_check_mark_desc: "ISI માર્ક, CRS R-નંબર અથવા હોલમાર્ક ચકાસો",
    qa_cert_help: "પ્રમાણીકરણ સહાય",
    qa_cert_help_desc: "MSME 6-પગલાનો રોડમેપ",
    qa_find_lab: "પ્રયોગશાળા શોધો",
    qa_find_lab_desc: "BIS-માન્યતા પ્રાપ્ત NABL પરીક્ષણ લેબ",
    qa_report_complaint: "ફરિયાદ નોંધાવો",
    qa_report_complaint_desc: "BIS કાયદા 2016 હેઠળ ફરિયાદ તૈયાર કરો",
    diff_badge: "ન્યાયાધીશ બેંચમાર્ક પ્રદર્શન",
    diff_title: "ડોકલિંગ + BGE-M3 સિમેન્ટીક ફેરફાર શોધ (શૂન્ય હેશિંગ)",
    diff_desc: "કલમ મુજબ દસ્તાવેજ સંસ્કરણ અને પ્રભાવ વિશ્લેષણ.",
    diff_demo1: "IS 2347:2017 કલમ 5.2 (સુધારેલ)",
    diff_demo2: "IS 17803:2022 (નવી કલમ ઉમેરાયેલ)",
    diff_demo3: "IS 13252:2010 (પુનઃક્રમાંકિત કલમ)",
    assistant_welcome: "નમસ્તે! હું નેક્સhumanસ્ટાન્ડર્ડ્સ છું, ભારતીય ધોરણો અને BIS સેવાઓ માટે તમારો AI સહાયક. કોઈપણ ઉત્પાદન વિશે પૂછો.",
    tab_consumer: "🛒 ગ્રાહક ચિહ્ન ચકાસણી",
    tab_startup: "🚀 સ્ટાર્ટઅપ 14-પગલાનો રોડમેપ",
    tab_builder: "🏭 તકનીકી વિશિષ્ટતાઓ",
    glossary_btn: "આ BIS શબ્દનો અર્થ શું છે?",
    input_placeholder: "કોઈપણ ધોરણ અથવા ઉત્પાદન વિશે પૂછો...",
    send_btn: "પૂછો",
    listening: "સાંભળી રહ્યો છું... બોલો",
    source_locked: "સ્ત્રોત-ચકાસાયેલ",
    unverified: "અચકાસાયેલ"
  },

  pa: {
    gov_india: "ਭਾਰਤ ਸਰਕਾਰ",
    bis_title: "ਬਿਊਰੋ ਆਫ਼ ਇੰਡੀਅਨ ਸਟੈਂਡਰਡਜ਼ (BIS)",
    demo_prototype: "ਡੈਮੋ ਪ੍ਰੋਟੋਟਾਈਪ",
    manakonline: "ਮਾਨਕਆਨਲਾਈਨ",
    app_title: "ਨੈਕਸਾਸਟੈਂਡਰਡਜ਼",
    app_badge: "SIH26107 ਸਹਾਇਕ",
    app_subtitle: "ਭਾਰਤੀ ਮਿਆਰਾਂ ਅਤੇ ਨਿਯਮਾਂ ਲਈ ਭਰੋਸੇਯੋਗ ਅਤੇ ਸਹੀ ਪਾਲਣਾ ਸਹਾਇਤਾ।",
    nav_assistant: "AI ਸਹਾਇਕ",
    nav_verify: "ਉਤਪਾਦ ਤਸਦੀਕ",
    nav_standards: "ਮਿਆਰ ਅਤੇ QCO",
    nav_compliance: "ਪਾਲਣਾ ਰੋਡਮੈਪ",
    nav_labs: "ਟੈਸਟਿੰਗ ਲੈਬਜ਼",
    nav_hallmarking: "ਹਾਲਮਾਰਕਿੰਗ",
    nav_grievance: "ਖਪਤਕਾਰ ਸ਼ਿਕਾਇਤ",
    nav_admin: "ਐਡਮਿਨ ਪੋਰਟਲ",
    side_group1: "1. ਇੱਕੋ ਥਾਂ ਪੁੱਛੋ",
    side_group2: "2. BIS ਨਿਯਮਾਂ ਨੂੰ ਸਮਝੋ",
    side_group3: "3. ਤੇਜ਼ ਉਤਪਾਦ ਤਸਦੀਕ",
    side_group4: "4. ਅਗਲਾ ਕਦਮ ਚੁੱਕੋ",
    side_group5: "5. ਸਰਕਾਰੀ ਰਜਿਸਟਰੀ",
    side_assistant: "AI ਗੱਲਬਾਤ ਸਹਾਇਕ",
    side_standards: "ਮਿਆਰ ਅਤੇ QCO ਐਕਸਪਲੋਰਰ",
    side_compare: "ਮਿਆਰ ਤੁਲਨਾ ਮੈਟ੍ਰਿਕਸ",
    side_certification: "ਸਰਟੀਫਿਕੇਸ਼ਨ ਸਕੀਮਾਂ",
    side_testing: "ਟੈਸਟਿੰਗ ਲੋੜਾਂ",
    side_verify: "ਉਤਪਾਦ ਤਸਦੀਕ (OCR)",
    side_hallmarking: "ਸੋਨੇ ਦੀ ਹਾਲਮਾਰਕਿੰਗ ਅਤੇ HUID",
    side_compliance: "ਪਾਲਣਾ ਰੋਡਮੈਪ",
    side_labs: "ਲੈਬ ਮੇਲ",
    side_grievance: "BIS ਸ਼ਿਕਾਇਤ ਸਹਾਇਕ",
    side_profile: "ਉਪਭੋਗਤਾ ਪ੍ਰੋਫਾਈਲ",
    side_settings: "ਸੈਟਿੰਗਾਂ ਅਤੇ LLM",
    side_admin_rag: "ਗਿਆਨ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ ਅਤੇ RAG",
    side_admin_docs: "ਦਸਤਾਵੇਜ਼ ਰਜਿਸਟਰੀ",
    hero_title: "ਦੱਸੋ ਕਿ ਤੁਹਾਡੇ ਕੋਲ ਕਿਹੜਾ ਉਤਪਾਦ ਹੈ ਜਾਂ ਤੁਸੀਂ ਕੀ ਬਣਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ।",
    hero_subtitle: "ਨੈਕਸਾਸਟੈਂਡਰਡਜ਼ ਗੁੰਝਲਦਾਰ BIS ਨਿਯਮਾਂ ਨੂੰ ਤੁਹਾਡੀ ਭੂਮਿਕਾ ਅਨੁਸਾਰ ਸਰਲ ਮਾਰਗਦਰਸ਼ਨ ਵਿੱਚ ਬਦਲਦਾ ਹੈ।",
    persona_consumer_title: "ਮੈਂ ਇੱਕ ਖਪਤਕਾਰ ਹਾਂ",
    persona_consumer_desc: "ਕਿਸੇ ਉਤਪਾਦ, BIS ਮਾਰਕ ਜਾਂ ਲਾਇਸੰਸ ਦੀ ਜਾਂਚ ਕਰੋ",
    persona_consumer_action: "ਮਾਰਕ ਅਤੇ ਪੈਕੇਜਿੰਗ ਦੀ ਜਾਂਚ ਕਰੋ →",
    persona_consumer_badge: "ਸਰਲ ਭਾਸ਼ਾ",
    persona_startup_title: "ਮੈਂ ਇੱਕ ਸਟਾਰਟਅੱਪ / MSME ਹਾਂ",
    persona_startup_desc: "ਜਾਣੋ ਕਿ ਇਸ ਉਤਪਾਦ ਨੂੰ ਬਣਾਉਣ ਜਾਂ ਵੇਚਣ ਲਈ ਮੈਨੂੰ ਕੀ ਚਾਹੀਦਾ ਹੈ",
    persona_startup_action: "ਸਟਾਰਟਅੱਪ ਨਿਰਮਾਣ ਗਾਈਡ →",
    persona_startup_badge: "14-ਕਦਮਾਂ ਦੀ ਚੈੱਕਲਿਸਟ",
    persona_builder_title: "ਮੈਂ ਇੱਕ ਨਿਰਮਾਤਾ / ਇੰਜੀਨੀਅਰ ਹਾਂ",
    persona_builder_desc: "ਮਿਆਰ, ਟੈਸਟ ਅਤੇ ਸਰਟੀਫਿਕੇਸ਼ਨ ਲੋੜਾਂ ਪ੍ਰਾਪਤ ਕਰੋ",
    persona_builder_action: "ਧਾਰਾਵਾਂ ਅਤੇ ਟੈਸਟ ਮਾਪਦੰਡ →",
    persona_builder_badge: "ਇੰਜੀਨੀਅਰਿੰਗ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
    search_role_prefix: "ਜਾਣਕਾਰੀ ਖੋਜੋ (ਸਰਗਰਮ ਭੂਮਿਕਾ: ",
    search_role_suffix: ")",
    switch_role: "ਭੂਮਿਕਾ ਬਦਲੋ:",
    role_consumer: "ਖਪਤਕਾਰ",
    role_startup: "ਸਟਾਰਟਅੱਪ",
    role_builder: "ਇੰਜੀਨੀਅਰ",
    search_placeholder: "ਜਿਵੇਂ 'ਮੋਬਾਈਲ', 'ਪ੍ਰੈਸ਼ਰ ਕੁੱਕਰ 'ਤੇ ਕਿਹੜਾ ਮਿਆਰ ਲਾਗੂ ਹੁੰਦਾ ਹੈ?'...",
    search_button: "ਜਾਣਕਾਰੀ ਖੋਜੋ →",
    try_scenarios: "ਤੇਜ਼ ਉਦਾਹਰਣਾਂ ਦੇਖੋ:",
    verify_photo_button: "ਮਾਰਕ / ਫੋਟੋ ਦੀ ਜਾਂਚ ਕਰੋ",
    qa_title: "ਤੇਜ਼ ਕਾਰਵਾਈਆਂ",
    qa_search_std: "ਮਿਆਰ ਖੋਜੋ",
    qa_search_std_desc: "ਲਾਗੂ IS ਨਿਯਮਾਂ ਦੀ ਪੜਚੋਲ ਕਰੋ",
    qa_verify_prod: "ਉਤਪਾਦ ਦੀ ਜਾਂਚ ਕਰੋ",
    qa_verify_prod_desc: "ਲੇਬਲ ਸਕੈਨ ਕਰੋ ਜਾਂ CM/L ਨੰਬਰ ਦਰਜ ਕਰੋ",
    qa_check_mark: "BIS ਮਾਰਕ ਦੀ ਜਾਂਚ ਕਰੋ",
    qa_check_mark_desc: "ISI ਮਾਰਕ, CRS R-ਨੰਬਰ ਜਾਂ ਹਾਲਮਾਰਕ ਦੀ ਜਾਂਚ ਕਰੋ",
    qa_cert_help: "ਸਰਟੀਫਿਕੇਸ਼ਨ ਸਹਾਇਤਾ",
    qa_cert_help_desc: "MSME 6-ਕਦਮਾਂ ਦਾ ਰੋਡਮੈਪ",
    qa_find_lab: "ਲੈਬ ਲੱਭੋ",
    qa_find_lab_desc: "BIS-ਮਾਨਤਾ ਪ੍ਰਾਪਤ NABL ਲੈਬਜ਼",
    qa_report_complaint: "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",
    qa_report_complaint_desc: "BIS ਐਕਟ 2016 ਅਧੀਨ ਸ਼ਿਕਾਇਤ ਤਿਆਰ ਕਰੋ",
    diff_badge: "ਜੱਜ ਬੈਂਚਮਾਰਕ ਪ੍ਰਦਰਸ਼ਨ",
    diff_title: "ਡਾਕਲਿੰਗ + BGE-M3 ਅਰਥਵਾਦੀ ਤਬਦੀਲੀ ਖੋਜ (ਜ਼ੀਰੋ ਹੈਸ਼ਿੰਗ)",
    diff_desc: "ਧਾਰਾ ਅਨੁਸਾਰ ਦਸਤਾਵੇਜ਼ ਸੰਸਕਰਣ ਅਤੇ ਪ੍ਰਭਾਵ ਵਿਸ਼ਲੇਸ਼ਣ।",
    diff_demo1: "IS 2347:2017 ਧਾਰਾ 5.2 (ਸੋਧੀ ਹੋਈ)",
    diff_demo2: "IS 17803:2022 (ਨਵੀਂ ਧਾਰਾ ਸ਼ਾਮਲ)",
    diff_demo3: "IS 13252:2010 (ਮੁੜ-ਨੰਬਰ ਕੀਤੀ ਧਾਰਾ)",
    assistant_welcome: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਨੈਕਸਾਸਟੈਂਡਰਡਜ਼ ਹਾਂ, ਭਾਰਤੀ ਮਿਆਰਾਂ ਅਤੇ BIS ਸੇਵਾਵਾਂ ਲਈ ਤੁਹਾਡਾ AI ਸਹਾਇਕ। ਕਿਸੇ ਵੀ ਉਤਪਾਦ ਬਾਰੇ ਪੁੱਛੋ।",
    tab_consumer: "🛒 ਖਪਤਕਾਰ ਮਾਰਕ ਤਸਦੀਕ",
    tab_startup: "🚀 ਸਟਾਰਟਅੱਪ 14-ਕਦਮਾਂ ਦਾ ਰੋਡਮੈਪ",
    tab_builder: "🏭 ਤਕਨੀਕੀ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
    glossary_btn: "ਇਸ BIS ਸ਼ਬਦ ਦਾ ਕੀ ਅਰਥ ਹੈ?",
    input_placeholder: "ਕਿਸੇ ਵੀ ਮਿਆਰ ਜਾਂ ਉਤਪਾਦ ਬਾਰੇ ਪੁੱਛੋ...",
    send_btn: "ਪੁੱਛੋ",
    listening: "ਸੁਣ ਰਿਹਾ ਹੈ... ਬੋਲੋ",
    source_locked: "ਸਰੋਤ-ਤਸਦੀਕਸ਼ੁਦਾ",
    unverified: "ਅਣ-ਤਸਦੀਕਸ਼ੁਦਾ"
  },

  or: {
    gov_india: "ଭାରତ ସରକାର",
    bis_title: "ଭାରତୀୟ ମାନକ ବ୍ୟୁରୋ (BIS)",
    demo_prototype: "ଡେମୋ ପ୍ରୋଟୋଟାଇପ୍",
    manakonline: "ମାନକଅନଲାଇନ୍",
    app_title: "ନେକ୍ସାଷ୍ଟାଣ୍ଡାର୍ଡ୍ସ",
    app_badge: "SIH26107 ସହାୟକ",
    app_subtitle: "ଭାରତୀୟ ମାନକ ଏବଂ ନିୟମାବଳୀ ପାଇଁ ବିଶ୍ୱସନୀୟ ଏବଂ ସଠିକ୍ ଅନୁପାଳନ ସମର୍ଥନ।",
    nav_assistant: "AI ସହାୟକ",
    nav_verify: "ଉତ୍ପାଦ ଯାଞ୍ଚ",
    nav_standards: "ମାନକ ଏବଂ QCO",
    nav_compliance: "ଅନୁପାଳନ ରୋଡମ୍ୟାପ୍",
    nav_labs: "ପରୀକ୍ଷଣ ଲାବୋରେଟୋରୀ",
    nav_hallmarking: "ହଲମାର୍କିଂ",
    nav_grievance: "ଗ୍ରାହକ ଅଭିଯୋଗ",
    nav_admin: "ଆଡମିନ୍ ପୋର୍ଟାଲ୍",
    side_group1: "୧. ଗୋଟିଏ ସ୍ଥାନରେ ପଚାରନ୍ତୁ",
    side_group2: "୨. BIS ନିୟମ ବୁଝନ୍ତୁ",
    side_group3: "୩. ଦ୍ରୁତ ଉତ୍ପାଦ ଯାଞ୍ଚ",
    side_group4: "୪. ପରବର୍ତ୍ତୀ ପଦକ୍ଷେପ ନିଅନ୍ତୁ",
    side_group5: "୫. ପ୍ରଶାସନିକ ପଞ୍ଜିକା",
    side_assistant: "AI ବାର୍ତ୍ତାଳାପ ସହାୟକ",
    side_standards: "ମାନକ ଏବଂ QCO ଅନୁସନ୍ଧାନ",
    side_compare: "ମାନକ ତୁଳନା ମ୍ୟାଟ୍ରିକ୍ସ",
    side_certification: "ପ୍ରମାଣପତ୍ର ଯୋଜନା",
    side_testing: "ପରୀକ୍ଷଣ ଆବଶ୍ୟକତା",
    side_verify: "ଉତ୍ପାଦ ଯାଞ୍ଚ (OCR)",
    side_hallmarking: "ସ୍ୱର୍ଣ୍ଣ ହଲମାର୍କିଂ ଏବଂ HUID",
    side_compliance: "ଅନୁପାଳନ ରୋଡମ୍ୟାପ୍",
    side_labs: "ଲାବୋରେଟୋରୀ ମେଳକ",
    side_grievance: "BIS ଅଭିଯୋଗ ସହାୟକ",
    side_profile: "ବ୍ୟବହାରକାରୀ ପ୍ରୋଫାଇଲ୍",
    side_settings: "ସେଟିଂସମୂହ ଏବଂ LLM",
    side_admin_rag: "ଜ୍ଞାନ ବିବରଣୀ ଏବଂ RAG",
    side_admin_docs: "ଦସ୍ତାବିଜ ପଞ୍ଜିକା",
    hero_title: "ଆପଣଙ୍କ ପାଖରେ କେଉଁ ଉତ୍ପାଦ ଅଛି ବା ଆପଣ କଣ ତିଆରି କରିବାକୁ ଚାହାଁନ୍ତି କୁହନ୍ତୁ।",
    hero_subtitle: "ନେକ୍ସାଷ୍ଟାଣ୍ଡାର୍ଡ୍ସ ଜଟିଳ BIS ନିୟମ ଏବଂ ଭାରତୀୟ ମାନକକୁ ଆପଣଙ୍କ ଭୂମିକା ଅନୁଯାୟୀ ସରଳ ମାର୍ଗଦର୍ଶନରେ ପରିଣତ କରେ।",
    persona_consumer_title: "ମୁଁ ଜଣେ ଗ୍ରାହକ",
    persona_consumer_desc: "ଏକ ଉତ୍ପାଦ, BIS ମାର୍କ, ଲାଇସେନ୍ସ ବା ଆବଶ୍ୟକତା ଯାଞ୍ଚ କରନ୍ତୁ",
    persona_consumer_action: "ମାର୍କ ଏବଂ ପ୍ୟାକେଜିଂ ଯାଞ୍ଚ କରନ୍ତୁ →",
    persona_consumer_badge: "ସରଳ ଭାଷା",
    persona_startup_title: "ମୁଁ ଏକ ଷ୍ଟାର୍ଟଅପ୍ / MSME",
    persona_startup_desc: "ଏହି ଉତ୍ପାଦ ତିଆରି ବା ବିକ୍ରୟ କରିବା ପାଇଁ ମୋତେ କଣ ଦରକାର ଜାଣନ୍ତୁ",
    persona_startup_action: "ଷ୍ଟାର୍ଟଅପ୍ ଉତ୍ପାଦନ ଗାଇଡ୍ →",
    persona_startup_badge: "୧୪-ପଦକ୍ଷେପ ଚେକଲିଷ୍ଟ",
    persona_builder_title: "ମୁଁ ଜଣେ ଉତ୍ପାଦ ନିର୍ମାତା / ଇଞ୍ଜିନିୟର",
    persona_builder_desc: "ମାନକ, ପରୀକ୍ଷଣ ଏବଂ ପ୍ରମାଣପତ୍ର ଆବଶ୍ୟକତା ପ୍ରାପ୍ତ କରନ୍ତୁ",
    persona_builder_action: "ଧାରା ଏବଂ ପରୀକ୍ଷଣ ପାରାମିଟର →",
    persona_builder_badge: "ଇଞ୍ଜିନିୟରିଂ ବିବରଣୀ",
    search_role_prefix: "ନିୟାମକ ସୂଚନା ଖୋଜନ୍ତୁ (ସକ୍ରିୟ ଭୂମିକା: ",
    search_role_suffix: ")",
    switch_role: "ଭୂମିକା ବଦଳାନ୍ତୁ:",
    role_consumer: "ଗ୍ରାହକ",
    role_startup: "ଷ୍ଟାର୍ଟଅପ୍",
    role_builder: "ଇଞ୍ଜିନିୟର",
    search_placeholder: "ଯଥା: 'ମୋବାଇଲ୍', 'ପ୍ରେସର କୁକର ପାଇଁ କେଉଁ ମାନକ ଲାଗୁ ହୁଏ?'...",
    search_button: "ସୂଚନା ଖୋଜନ୍ତୁ →",
    try_scenarios: "ଦ୍ରୁତ ଉଦାହରଣ ଦେଖନ୍ତୁ:",
    verify_photo_button: "ମାର୍କ / ଫଟୋ ଯାଞ୍ଚ କରନ୍ତୁ",
    qa_title: "ଦ୍ରୁତ ପଦକ୍ଷେପ",
    qa_search_std: "ମାନକ ଖୋଜନ୍ତୁ",
    qa_search_std_desc: "ପ୍ରଯୁଜ୍ୟ IS ନିୟମାବଳୀ ଅନୁସନ୍ଧାନ କରନ୍ତୁ",
    qa_verify_prod: "ଉତ୍ପାଦ ଯାଞ୍ଚ କରନ୍ତୁ",
    qa_verify_prod_desc: "ଲେବଲ୍ ସ୍କାନ୍ କରନ୍ତୁ କିମ୍ବା CM/L ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ",
    qa_check_mark: "BIS ମାର୍କ ଯାଞ୍ଚ କରନ୍ତୁ",
    qa_check_mark_desc: "ISI ମାର୍କ, CRS R-ନମ୍ବର ବା ହଲମାର୍କ ଯାଞ୍ଚ କରନ୍ତୁ",
    qa_cert_help: "ପ୍ରମାଣପତ୍ର ସହାୟତା",
    qa_cert_help_desc: "MSME ୬-ପଦକ୍ଷେପ ରୋଡମ୍ୟାପ୍",
    qa_find_lab: "ଲାବୋରେଟୋରୀ ଖୋଜନ୍ତୁ",
    qa_find_lab_desc: "BIS-ସ୍ୱୀକୃତିପ୍ରାପ୍ତ NABL ପରୀକ୍ଷଣ ଲାବ୍",
    qa_report_complaint: "ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ",
    qa_report_complaint_desc: "BIS ଅଧିନିୟମ ୨୦୧୬ ଅନୁଯାୟୀ ଅଭିଯୋଗ ପ୍ରସ୍ତୁତ କରନ୍ତୁ",
    diff_badge: "ବିଚାରପତି ବେଞ୍ଚମାର୍କ ପ୍ରଦର୍ଶନ",
    diff_title: "ଡକଲିଙ୍ଗ + BGE-M3 ସେମାଣ୍ଟିକ ପରିବର୍ତ୍ତନ ଚିହ୍ନଟ (ଶୂନ୍ୟ ହ୍ୟାସିଂ)",
    diff_desc: "ଧାରା ଅନୁସାରେ ଦସ୍ତାବିଜ ସଂସ୍କରଣ ଏବଂ ପ୍ରଭାବ ବିଶ୍ଳେଷଣ।",
    diff_demo1: "IS 2347:2017 ଧାରା ୫.୨ (ସଂଶୋଧିତ)",
    diff_demo2: "IS 17803:2022 (ନୂତନ ଧାରା ଯୋଡ଼ାଯାଇଛି)",
    diff_demo3: "IS 13252:2010 (ପୁନଃ-ସଂଖ୍ୟାକୃତ ଧାରା)",
    assistant_welcome: "ନମସ୍କାର! ମୁଁ ନେକ୍ସାଷ୍ଟାଣ୍ଡାର୍ଡ୍ସ, ଭାରତୀୟ ମାନକ ଏବଂ BIS ସେବା ପାଇଁ ଆପଣଙ୍କ AI ସହାୟକ। ଯେକୌଣସି ଉତ୍ପାଦ ବିଷୟରେ ପଚାରନ୍ତୁ।",
    tab_consumer: "🛒 ଗ୍ରାହକ ମାର୍କ ଯାଞ୍ଚ",
    tab_startup: "🚀 ଷ୍ଟାର୍ਟଅପ୍ ୧୪-ପଦକ୍ଷେପ ରୋଡମ୍ୟାପ୍",
    tab_builder: "🏭 ବୈଷୟିକ ବିବରଣୀ",
    glossary_btn: "ଏହି BIS ଶବ୍ଦର ଅର୍ଥ କଣ?",
    input_placeholder: "ଯେକୌଣସି ମାନକ ବା ଉତ୍ପାଦ ବିଷୟରେ ପଚାରନ୍ତୁ...",
    send_btn: "ପଚାରନ୍ତୁ",
    listening: "ଶୁଣୁଛି... କୁହନ୍ତୁ",
    source_locked: "ଉତ୍ସ-ଯାଞ୍ଚକୃତ",
    unverified: "ଅଯାଞ୍ଚକୃତ"
  }
};

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string, defaultText?: string) => string;
  languages: LanguageOption[];
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string, defaultText?: string) => defaultText || key,
  languages: SUPPORTED_LANGUAGES
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<string>("en");

  useEffect(() => {
    try {
      const saved = localStorage.getItem("bis_smartassist_lang");
      if (saved && TRANSLATIONS[saved]) {
        setLanguageState(saved);
        document.documentElement.lang = saved;
      }
    } catch (e) {
      // ignore localStorage errors in SSR/strict envs
    }
  }, []);

  const setLanguage = (newLang: string) => {
    setLanguageState(newLang);
    try {
      localStorage.setItem("bis_smartassist_lang", newLang);
      document.documentElement.lang = newLang;
      // Dispatch custom window event so all components / tabs synchronize immediately
      window.dispatchEvent(new CustomEvent("bis_language_changed", { detail: newLang }));
    } catch (e) {
      // ignore
    }
  };

  const t = (key: string, defaultText?: string): string => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    const enDict = TRANSLATIONS.en;
    if (enDict && enDict[key]) {
      return enDict[key];
    }
    return defaultText || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
